/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    DiceGame: {
      address:
        "0x6004d2cb0fea63dff50e334390bacb1f1488f624520e5f2e4454801910d4ff9",
      abi: [
        {
          type: "impl",
          name: "DiceGameImpl",
          interface_name: "contracts::DiceGame::IDiceGame",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "openzeppelin_token::erc20::interface::IERC20CamelDispatcher",
          members: [
            {
              name: "contract_address",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::DiceGame::IDiceGame",
          items: [
            {
              type: "function",
              name: "roll_dice",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "last_dice_value",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "nonce",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "prize",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "eth_token_dispatcher",
              inputs: [],
              outputs: [
                {
                  type: "openzeppelin_token::erc20::interface::IERC20CamelDispatcher",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "eth_token_address",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::DiceGame::DiceGame::Roll",
          kind: "struct",
          members: [
            {
              name: "player",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "roll",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::DiceGame::DiceGame::Winner",
          kind: "struct",
          members: [
            {
              name: "winner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::DiceGame::DiceGame::Event",
          kind: "enum",
          variants: [
            {
              name: "Roll",
              type: "contracts::DiceGame::DiceGame::Roll",
              kind: "nested",
            },
            {
              name: "Winner",
              type: "contracts::DiceGame::DiceGame::Winner",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x481fa05b3ae9766763c2df71ffd19616815e1f79da4cbe41ba4b59f2265430e",
    },
  },
} as const;

export default deployedContracts;
